language: java
jdk: openjdk11
sudo: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
   - CODECOV_TOKEN="301ac758-da71-4c24-9306-1c15e5a59fd6"
notifications:
  email:
    recipients:
      - moralev.alexandr@yandex.ru
    on_success: never
    on_failure: always
services:
    - postgresql

before_install:
    - psql -c 'create database tracker_db;' -U postgres
    - psql -c 'create database users_app;' -U postgres
    - psql -c 'create database vacancies_db;' -U postgres
    - psql -c 'create user admin with password 'admin';' -U postgres
    - psql -c 'grant all privileges on database tracker_db to admin;' -U postgres
    - psql -c 'grant all privileges on database users_app to admin;' -U postgres
    - psql -c 'grant all privileges on database vacancies_db to admin;' -U postgres