language: java
jdk: openjdk11
sudo: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
   - CODECOV_TOKEN="301ac758-da71-4c24-9306-1c15e5a59fd6"
notifications:
  email:
    recipients:
      - moralev.alexandr@yandex.ru
    on_success: never
    on_failure: always
services:
    - postgresql

before_install:
    - psql -c 'create database tracker_db;' -U postgres
    - psql -c 'create database users_app;' -U postgres
    - psql -c 'create database vacancies_db;' -U postgres
    - psql -c 'create database cinema_app;' -U postgres
    - psql -c 'create database test_cinema_app;' -U postgres
    - psql -c 'create database auto_crash;' -U postgres
    - psql -c 'create database test_auto_crash;' -U postgres
    - psql -c 'create database todo_list;' -U postgres
    - psql -c 'create database test_todo_list;' -U postgres
    - psql -c 'create database car_marketplace;' -U postgres
    - psql -c 'create database test_car_marketplace;' -U postgres